import { Link } from 'react-router';
import { motion } from 'motion/react';
import {
  Recycle, CheckCircle2, Leaf, Building2, ShieldCheck,
  FlaskConical, HardHat, Monitor, Stethoscope,
  Briefcase, Construction, Sofa, TreePine,
  Wrench, Home,
  AlertTriangle, Factory, Package,
} from 'lucide-react';
import { ImageWithFallback } from '@/app/components/figma/ImageWithFallback';
import { ServicePageHero } from '@/app/components/service-page/ServicePageHero';
import ewasteHeroImage from "@/assets/office-space-removal-image.avif";
import wasteRemovalImage from "@/assets/waste-removal-image.avif";

/* ── Hazardous Waste ── */
const hazardousWaste = [
  {
    title: "Chemicals & Solvents",
    description: "Paints, oils, acids, and industrial chemical waste — collected and disposed of through licensed hazardous waste facilities.",
    icon: <FlaskConical className="w-5 h-5" />,
  },
  {
    title: "Construction Hazards",
    description: "Asbestos insulation, treated timber, and contaminated soils handled with full safety protocols and regulatory compliance.",
    icon: <HardHat className="w-5 h-5" />,
  },
  {
    title: "WEEE (Electronic Waste)",
    description: "Computer monitors, fluorescent tubes, and heavy machinery with hazardous components — processed through certified e-waste recycling.",
    icon: <Monitor className="w-5 h-5" />,
  },
  {
    title: "Healthcare Waste",
    description: "Clinical, medical, or sharps waste requiring specialised tracking, secure transport, and compliant incineration or treatment.",
    icon: <Stethoscope className="w-5 h-5" />,
  },
];

/* ── Non-Hazardous Commercial & Industrial ── */
const commercialWaste = [
  {
    title: "Business Waste",
    description: "General office waste, retail packaging, food waste, and cardboard — regular or one-off collections for businesses of any size.",
    icon: <Briefcase className="w-5 h-5" />,
  },
  {
    title: "Construction & Demolition",
    description: "Brick, concrete, plasterboard, tiles, and metal rubble removed efficiently from building sites and renovation projects.",
    icon: <Construction className="w-5 h-5" />,
  },
  {
    title: "Bulky Items",
    description: "Office furniture, mattresses, and large-scale industrial fixtures collected and responsibly recycled or disposed of.",
    icon: <Sofa className="w-5 h-5" />,
  },
  {
    title: "Green Waste",
    description: "Large volumes of garden, agricultural, or landscaping clearance materials composted or recycled through approved facilities.",
    icon: <TreePine className="w-5 h-5" />,
  },
];

/* ── Household Waste (by Third Parties) ── */
const householdWaste = [
  {
    title: "Contractor Waste",
    description: "Waste generated by a builder, plumber, or gardener working at a private home — we collect and dispose of it on their behalf.",
    icon: <Wrench className="w-5 h-5" />,
  },
  {
    title: "House Clearances",
    description: "Complete property or estate clearances managed professionally — from single rooms to full houses, we handle every item.",
    icon: <Home className="w-5 h-5" />,
  },
];

const keyFeatures = [
  "Licensed Waste Carrier",
  "Hazardous & Non-Hazardous Waste",
  "WEEE-Compliant E-Waste Recycling",
  "Secure Data Destruction",
  "Construction & Demolition Clearance",
  "Carbon-Conscious Waste Management",
];

const whoWeServe = [
  {
    title: "Businesses & Corporations",
    desc: "Office clearouts, IT refresh cycles, and regular commercial waste collections with full compliance documentation.",
    icon: <Building2 className="w-5 h-5" />,
  },
  {
    title: "Construction Sites",
    desc: "Rubble, demolition debris, plasterboard, and hazardous construction materials removed safely and efficiently.",
    icon: <Construction className="w-5 h-5" />,
  },
  {
    title: "Healthcare Facilities",
    desc: "Clinical and medical waste disposal with strict compliance to environmental, safety, and data standards.",
    icon: <Stethoscope className="w-5 h-5" />,
  },
  {
    title: "Industrial & Manufacturing",
    desc: "Chemical waste, solvents, heavy machinery components, and large-scale industrial fixture disposal.",
    icon: <Factory className="w-5 h-5" />,
  },
  {
    title: "Residential Customers",
    desc: "Household appliance pickups, garden clearance, and property clear-outs for homeowners and landlords.",
    icon: <Home className="w-5 h-5" />,
  },
  {
    title: "Government & Education",
    desc: "Compliant waste disposal with audit trails and certification for public sector and educational institutions.",
    icon: <ShieldCheck className="w-5 h-5" />,
  },
];

/* ── Waste Category Section Component ── */
const WasteCategorySection = ({
  color,
  colorClass,
  bgClass,
  borderClass,
  iconBgClass,
  label,
  items,
  index: sectionIndex,
}: {
  color: string;
  colorClass: string;
  bgClass: string;
  borderClass: string;
  iconBgClass: string;
  label: string;
  items: { title: string; description: string; icon: React.ReactNode }[];
  index: number;
}) => (
  <motion.div
    initial={{ opacity: 0, y: 24 }}
    whileInView={{ opacity: 1, y: 0 }}
    viewport={{ once: true }}
    transition={{ duration: 0.5, delay: sectionIndex * 0.1 }}
  >
    {/* Category Header */}
    <div className="flex items-center gap-3 mb-6">
      <span className={`w-4 h-4 rounded-sm ${colorClass} flex-shrink-0`} />
      <h3 className="text-xl sm:text-2xl font-extrabold text-[#1C1C1C]">{label}</h3>
    </div>

    {/* Cards */}
    <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 sm:gap-5">
      {items.map((item, idx) => (
        <motion.div
          key={item.title}
          initial={{ opacity: 0, y: 16 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ delay: idx * 0.07, duration: 0.4 }}
          className={`rounded-2xl p-5 sm:p-6 border ${borderClass} ${bgClass} hover:bg-white hover:shadow-lg transition-all group`}
        >
          <div className={`w-10 h-10 rounded-xl ${iconBgClass} flex items-center justify-center mb-4 text-[#0E3A6D] group-hover:bg-[#0E3A6D] group-hover:text-white transition-colors`}>
            {item.icon}
          </div>
          <h4 className="text-base sm:text-lg font-bold text-[#1C1C1C] mb-2">{item.title}</h4>
          <p className="text-[#6B7280] text-sm leading-relaxed">{item.description}</p>
        </motion.div>
      ))}
    </div>
  </motion.div>
);

export const WasteRemovalPage = () => {
  return (
    <div className="bg-white">
      <ServicePageHero
        title="Certified Waste Removal"
        description="We are a licensed waste carrier specialising in the safe collection, removal, and disposal of almost all types of waste — including commercial, industrial, and hazardous materials."
        icon={<Recycle className="h-16 w-16 text-[#F4C430]" />}
        background={
          <ImageWithFallback
            src={ewasteHeroImage}
            alt="Waste Removal Services"
            className="h-full w-full object-cover"
          />
        }
        actions={
          <Link
            to="/contact?service=waste-removal"
            className="whitespace-nowrap rounded-full bg-[#D62828] px-10 py-4 font-bold text-white transition-all hover:bg-[#B91C1C]"
          >
            Schedule Waste Collection
          </Link>
        }
      />

      {/* Why Choose Us — Split Layout */}
      <section className="py-20 sm:py-24 bg-[#F7F9FC]">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex flex-col lg:flex-row gap-12 lg:gap-16 items-start">
            {/* Left — Intro */}
            <motion.div
              initial={{ opacity: 0, x: -20 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.5 }}
              className="w-full lg:w-5/12 lg:sticky lg:top-32"
            >
              <div className="w-12 h-1.5 bg-[#F4C430] rounded-full mb-6" />
              <h2 className="text-3xl sm:text-4xl font-extrabold text-[#1C1C1C] mb-6 leading-tight">
                Comprehensive Waste Removal Solutions
              </h2>
              <p className="text-[#6B7280] text-base sm:text-lg leading-relaxed mb-8">
                From hazardous chemicals and construction debris to electronic waste and household clearances — we handle it all responsibly and in full compliance with environmental regulations. Our licensed team ensures every item is collected, transported, and processed through approved facilities.
              </p>
              <Link
                to="/contact?service=waste-removal"
                className="inline-flex items-center gap-2 bg-[#0E3A6D] text-white px-8 py-3.5 rounded-full font-bold hover:bg-[#0C2F58] transition-all shadow-lg hover:shadow-xl"
              >
                Get a Free Quote
              </Link>
            </motion.div>

            {/* Right — Key Features Grid */}
            <div className="w-full lg:w-7/12">
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 sm:gap-5">
                {keyFeatures.map((feature, index) => (
                  <motion.div
                    key={feature}
                    initial={{ opacity: 0, y: 16 }}
                    whileInView={{ opacity: 1, y: 0 }}
                    viewport={{ once: true }}
                    transition={{ delay: index * 0.08, duration: 0.4 }}
                    className="flex items-start gap-4 bg-white rounded-2xl p-5 sm:p-6 border border-[#0E3A6D]/8 shadow-sm hover:shadow-md transition-all"
                  >
                    <div className="flex-shrink-0 w-10 h-10 rounded-xl bg-[#0E3A6D]/8 flex items-center justify-center">
                      <CheckCircle2 className="w-5 h-5 text-[#0E3A6D]" />
                    </div>
                    <span className="text-[#1C1C1C] font-semibold text-[0.95rem] leading-snug pt-2">{feature}</span>
                  </motion.div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Waste Categories — Main Content */}
      <section className="py-20 sm:py-24">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <motion.div
            initial={{ opacity: 0, y: 16 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="text-center mb-14 sm:mb-16"
          >
            <div className="w-12 h-1.5 bg-[#F4C430] rounded-full mb-6 mx-auto" />
            <h2 className="text-3xl font-extrabold text-[#1C1C1C] mb-4">What We Remove</h2>
            <p className="text-[#6B7280] max-w-2xl mx-auto text-base sm:text-lg">
              We are registered to remove almost all types of waste. Here's a breakdown of the primary categories we handle.
            </p>
          </motion.div>

          <div className="space-y-14 sm:space-y-16">
            {/* Hazardous Waste */}
            <WasteCategorySection
              color="red"
              colorClass="bg-[#D62828]"
              bgClass="bg-red-50/60"
              borderClass="border-[#D62828]/15"
              iconBgClass="bg-[#D62828]/10"
              label="Hazardous Waste"
              items={hazardousWaste}
              index={0}
            />

            {/* Non-Hazardous Commercial & Industrial */}
            <WasteCategorySection
              color="green"
              colorClass="bg-[#16A34A]"
              bgClass="bg-green-50/60"
              borderClass="border-[#16A34A]/15"
              iconBgClass="bg-[#16A34A]/10"
              label="Non-Hazardous Commercial & Industrial Waste"
              items={commercialWaste}
              index={1}
            />

            {/* Household Waste */}
            <WasteCategorySection
              color="gray"
              colorClass="bg-[#9CA3AF]"
              bgClass="bg-[#F7F9FC]"
              borderClass="border-[#0E3A6D]/8"
              iconBgClass="bg-[#0E3A6D]/8"
              label="Household Waste (by Third Parties)"
              items={householdWaste}
              index={2}
            />
          </div>
        </div>
      </section>

      {/* Secure & Compliant — Split Feature */}
      <section className="py-20 sm:py-24 bg-[#F7F9FC]">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex flex-col lg:flex-row items-center gap-10 lg:gap-12">
            <motion.div
              initial={{ opacity: 0, scale: 0.96 }}
              whileInView={{ opacity: 1, scale: 1 }}
              viewport={{ once: true }}
              transition={{ duration: 0.6 }}
              className="relative rounded-3xl overflow-hidden group w-full lg:w-1/2 h-72 sm:h-96"
            >
              <ImageWithFallback
                src={wasteRemovalImage}
                alt="Licensed waste removal and recycling"
                className="w-full h-full object-cover group-hover:scale-110 transition-transform duration-700"
              />
              <div className="absolute inset-0 bg-gradient-to-t from-[#0E3A6D]/80 to-transparent flex items-end p-6 sm:p-8">
                <p className="text-white font-bold text-lg">Licensed & Compliant Waste Disposal</p>
              </div>
            </motion.div>
            <motion.div
              initial={{ opacity: 0, x: 20 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.5, delay: 0.1 }}
              className="w-full lg:w-1/2"
            >
              <div className="w-12 h-1.5 bg-[#F4C430] rounded-full mb-6" />
              <h2 className="text-2xl sm:text-3xl font-extrabold text-[#1C1C1C] mb-6">Safe, Secure & Fully Compliant</h2>
              <p className="text-[#6B7280] text-base sm:text-lg leading-relaxed mb-8">
                Every waste stream we handle is processed through approved and licensed facilities. We provide full documentation, duty of care paperwork, and certificates for your compliance records.
              </p>
              <ul className="space-y-3 sm:space-y-4 mb-8 sm:mb-10">
                {[
                  "Licensed waste carrier registration",
                  "Duty of care documentation provided",
                  "Hazardous waste consignment notes",
                  "WEEE-compliant e-waste recycling",
                  "Full audit trail & certification",
                ].map((item) => (
                  <li key={item} className="flex items-center gap-3.5 text-[#1C1C1C]">
                    <span className="w-8 h-8 rounded-lg bg-[#F4C430]/15 flex items-center justify-center flex-shrink-0">
                      <CheckCircle2 className="w-4 h-4 text-[#0E3A6D]" />
                    </span>
                    <span className="font-semibold text-sm sm:text-base">{item}</span>
                  </li>
                ))}
              </ul>
              <Link
                to="/contact?service=waste-removal"
                className="bg-[#D62828] text-white px-8 py-3.5 rounded-full font-bold hover:bg-[#B91C1C] transition-all shadow-lg hover:shadow-xl inline-block text-sm sm:text-base"
              >
                Request Waste Collection
              </Link>
            </motion.div>
          </div>
        </div>
      </section>

      {/* Who We Serve */}
      <section className="py-20 sm:py-24">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <motion.div
            initial={{ opacity: 0, y: 16 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="text-center mb-14 sm:mb-16"
          >
            <div className="w-12 h-1.5 bg-[#F4C430] rounded-full mb-6 mx-auto" />
            <h2 className="text-3xl font-extrabold text-[#1C1C1C] mb-4">Who We Serve</h2>
            <p className="text-[#6B7280] max-w-2xl mx-auto text-base sm:text-lg">
              From residential pickups to large-scale industrial waste disposal — we serve clients of every size and sector.
            </p>
          </motion.div>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-5 sm:gap-6">
            {whoWeServe.map((item, index) => (
              <motion.div
                key={item.title}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: index * 0.08, duration: 0.4 }}
                className="bg-[#F7F9FC] rounded-2xl p-6 sm:p-7 border border-[#0E3A6D]/8 hover:bg-white hover:shadow-lg transition-all group"
              >
                <div className="w-11 h-11 rounded-xl bg-[#0E3A6D]/8 flex items-center justify-center mb-5 group-hover:bg-[#0E3A6D] group-hover:text-white text-[#0E3A6D] transition-colors">
                  {item.icon}
                </div>
                <h3 className="text-lg font-bold text-[#1C1C1C] mb-2">{item.title}</h3>
                <p className="text-[#6B7280] text-sm leading-relaxed">{item.desc}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-20 bg-[#0E3A6D]">
        <div className="max-w-4xl mx-auto px-4 text-center">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.5 }}
          >
            <div className="w-10 h-10 rounded-full bg-white/10 flex items-center justify-center mx-auto mb-6">
              <Leaf className="w-5 h-5 text-[#F4C430]" />
            </div>
            <h2 className="text-2xl sm:text-3xl font-extrabold mb-6 text-white">Need Waste Removed Responsibly?</h2>
            <p className="text-blue-100 mb-10 text-base sm:text-lg max-w-2xl mx-auto">
              Whether it's hazardous chemicals, construction rubble, electronic equipment, or a full house clearance — we'll handle it safely and compliantly.
            </p>
            <div className="flex flex-col sm:flex-row flex-wrap justify-center gap-4">
              <Link
                to="/contact?service=waste-removal"
                className="bg-[#D62828] text-white px-10 py-4 rounded-full font-bold hover:bg-[#B91C1C] transition-all shadow-lg hover:shadow-xl inline-block"
              >
                Get a Free Waste Removal Quote
              </Link>
              <Link
                to="/services/clearance"
                className="bg-white/10 text-white px-10 py-4 rounded-full font-bold hover:bg-white/20 transition-all border border-white/20 inline-block"
              >
                View Clearance Services
              </Link>
            </div>
          </motion.div>
        </div>
      </section>
    </div>
  );
};
